# Generated by Django 2.2.7 on 2019-11-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='dude'),
            preserve_default=False,
        ),
    ]
